server: hub.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESS_KEY

common_caps:
  bstack:options:
    os: OS X
    buildName: browserstack-build-1
    osVersion: Mojave
    sessionName: BStack local capybara
    projectName: BrowserStack Samples
    debug: true
    local: true
    useW3C: true

browser_caps:
  - browserName: Chrome
    browserVersion: 'latest'
