server: hub.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESS_KEY

common_caps:
  build: browserstack-build-1
  browserstack.debug: true
  name: BStack parallel capybara

browser_caps:
- browser: chrome
- browser: firefox
- browser: edge
- browser: safari
