server: hub.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESS_KEY

common_caps:
  bstack:options:
    os: Windows
    buildName: browserstack-build-1
    osVersion: '10'
    sessionName: BStack single capybara
    projectName: BrowserStack Samples
    debug: true
    useW3C: true

browser_caps:
  - browserName: Chrome
    browserVersion: 'latest'
