server: hub-cloud.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESS_KEY

common_caps:
  browserstack.use_w3c: true
  bstack:options:
    os: Windows
    buildName: browserstack-build-1
    osVersion: '7'
    sessionName: BStack single capybara
    projectName: Test Application
    debug: true

browser_caps:
  - browserName: Chrome
    browserVersion: '70.0'
